defaults:
  - model: xgboost # xgboost or xgboost
  - _self_
exp:
  seed: 12345
  threshold: 0.4 # for transforming y_pred_proba -> y_pred, since recall is more critical (minimizing false negatives)
data:
  dir: ./processed_data/final_df.csv
  target_var: is_default
  subset: true # use just a subset of features, only applicable for xgboost
  ordinal_cat_feats: # Ordinal categorical are categorical values for which the order is meaningful, for example for cat_number_accounts: '3' > '2' > '1'
    - cat_number_accounts
    - cat_number_loans_accounts
    - cat_number_client_calls_from_BANK
  nominal_cat_feats: # I will treat postal codes as nominal features because the ordering of the codes doesn't provide any meaningful information about the relationships between the areas they represent.
    - loan_reason
    - gender
    - religion
    - employment
    - postal_code
  numerical_feats:
    - age
    - relationship_length
    - average_salary
    - average_current_acc_balance
    - average_monthly_balance
  numerical_skewed_feats:
    - requested_amount
    - payback_amount
    - installment
    - number_client_calls_to_BANK
    - average_saving_account_balance
    - average_credit_card_balance
    - average_debt_to_income_ratio
  cat_feats_subset:
    - cat_number_client_calls_from_BANK
  numerical_feats_subset:
    - payback_amount
    - average_debt_to_income_ratio
    - average_salary
hydra:
  run:
    dir: ${model.save_result_dir}